root = "."
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "templ generate && sqlc generate && tailwindcss -i input.css -o public/output.css && go build -tags dev -o ./tmp/main ."
delay = 50
exclude_dir = ["tmp", "vendor", "data", "public"]
exclude_file = []
exclude_regex = ["_test.go", ".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "templ", "sql"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
