// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package data

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDeveloperBySlug = `-- name: GetDeveloperBySlug :one
SELECT id, slug, name, bio_md, website_url, logo_key, socials, igdb_id, created_at, updated_at, last_igdb_sync_at FROM developers
WHERE slug = $1
`

func (q *Queries) GetDeveloperBySlug(ctx context.Context, slug string) (Developer, error) {
	row := q.db.QueryRow(ctx, getDeveloperBySlug, slug)
	var i Developer
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.BioMd,
		&i.WebsiteUrl,
		&i.LogoKey,
		&i.Socials,
		&i.IgdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastIgdbSyncAt,
	)
	return i, err
}

const getGameBySlug = `-- name: GetGameBySlug :one

SELECT id, slug, title, tagline, description_md, gem_note_md, release_date, release_status, steam_appid, igdb_id, website_url, steam_review_pct, steam_review_count, editorial_score, gem_score, created_at, updated_at, trailer_youtube_id, last_steam_sync_at, last_igdb_sync_at FROM games
WHERE slug = $1
`

// Catalog: games, developers and their relations (page-facing reads).
//
// Game cards: game_cards is a SQL view (migration 000013) that pre-joins the
// primary developer (first developer alphabetically) and card media (first
// header by position, else first capsule — 460x215 headers fit cards best).
// Card-returning queries select from it so all views share data.GameCards.
func (q *Queries) GetGameBySlug(ctx context.Context, slug string) (Game, error) {
	row := q.db.QueryRow(ctx, getGameBySlug, slug)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Tagline,
		&i.DescriptionMd,
		&i.GemNoteMd,
		&i.ReleaseDate,
		&i.ReleaseStatus,
		&i.SteamAppid,
		&i.IgdbID,
		&i.WebsiteUrl,
		&i.SteamReviewPct,
		&i.SteamReviewCount,
		&i.EditorialScore,
		&i.GemScore,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrailerYoutubeID,
		&i.LastSteamSyncAt,
		&i.LastIgdbSyncAt,
	)
	return i, err
}

const getGameCardBySlug = `-- name: GetGameCardBySlug :one
SELECT gc.id, gc.slug, gc.title, gc.tagline, gc.release_date, gc.release_status, gc.gem_score, gc.developer_name, gc.developer_slug, gc.media_key
FROM game_cards gc
WHERE gc.slug = $1
`

func (q *Queries) GetGameCardBySlug(ctx context.Context, slug string) (GameCard, error) {
	row := q.db.QueryRow(ctx, getGameCardBySlug, slug)
	var i GameCard
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Tagline,
		&i.ReleaseDate,
		&i.ReleaseStatus,
		&i.GemScore,
		&i.DeveloperName,
		&i.DeveloperSlug,
		&i.MediaKey,
	)
	return i, err
}

const listAllGameSlugs = `-- name: ListAllGameSlugs :many
SELECT slug FROM games ORDER BY slug
`

// Sitemap.
func (q *Queries) ListAllGameSlugs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAllGameSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeveloperGameRoles = `-- name: ListDeveloperGameRoles :many
SELECT gd.role
FROM game_developers gd
WHERE gd.game_id = $1 AND gd.developer_id = $2
`

type ListDeveloperGameRolesParams struct {
	GameID      pgtype.UUID
	DeveloperID pgtype.UUID
}

// Roles a developer has for a given game (0..2 rows).
func (q *Queries) ListDeveloperGameRoles(ctx context.Context, arg ListDeveloperGameRolesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listDeveloperGameRoles, arg.GameID, arg.DeveloperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameDevelopers = `-- name: ListGameDevelopers :many
SELECT d.id, d.slug, d.name, d.bio_md, d.website_url, d.logo_key, d.socials, d.igdb_id, d.created_at, d.updated_at, d.last_igdb_sync_at, gd.role
FROM game_developers gd
JOIN developers d ON d.id = gd.developer_id
WHERE gd.game_id = $1
ORDER BY gd.role, d.name
`

type ListGameDevelopersRow struct {
	ID             pgtype.UUID
	Slug           string
	Name           string
	BioMd          string
	WebsiteUrl     string
	LogoKey        string
	Socials        []byte
	IgdbID         pgtype.Int8
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	LastIgdbSyncAt pgtype.Timestamptz
	Role           string
}

// All companies attached to a game, with their role (developer/publisher).
func (q *Queries) ListGameDevelopers(ctx context.Context, gameID pgtype.UUID) ([]ListGameDevelopersRow, error) {
	rows, err := q.db.Query(ctx, listGameDevelopers, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGameDevelopersRow
	for rows.Next() {
		var i ListGameDevelopersRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.BioMd,
			&i.WebsiteUrl,
			&i.LogoKey,
			&i.Socials,
			&i.IgdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastIgdbSyncAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameMedia = `-- name: ListGameMedia :many
SELECT id, game_id, kind, key, source_url, position, created_at, updated_at FROM media
WHERE game_id = $1
ORDER BY kind, position
`

func (q *Queries) ListGameMedia(ctx context.Context, gameID pgtype.UUID) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listGameMedia, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Kind,
			&i.Key,
			&i.SourceUrl,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameTags = `-- name: ListGameTags :many
SELECT t.id, t.slug, t.name, t.created_at, t.updated_at
FROM game_tags gt
JOIN tags t ON t.id = gt.tag_id
WHERE gt.game_id = $1
ORDER BY t.name
`

func (q *Queries) ListGameTags(ctx context.Context, gameID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listGameTags, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesByDeveloper = `-- name: ListGamesByDeveloper :many
SELECT gc.id, gc.slug, gc.title, gc.tagline, gc.release_date, gc.release_status, gc.gem_score, gc.developer_name, gc.developer_slug, gc.media_key
FROM game_cards gc
JOIN game_developers gd
  ON gd.game_id = gc.id
 AND gd.developer_id = $1
 AND gd.role = 'developer'
WHERE gc.id != $2
ORDER BY gc.release_date DESC NULLS LAST
`

type ListGamesByDeveloperParams struct {
	DeveloperID pgtype.UUID
	ID          pgtype.UUID
}

// "More from this developer" — excludes the game the viewer is on.
func (q *Queries) ListGamesByDeveloper(ctx context.Context, arg ListGamesByDeveloperParams) ([]GameCard, error) {
	rows, err := q.db.Query(ctx, listGamesByDeveloper, arg.DeveloperID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameCard
	for rows.Next() {
		var i GameCard
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Tagline,
			&i.ReleaseDate,
			&i.ReleaseStatus,
			&i.GemScore,
			&i.DeveloperName,
			&i.DeveloperSlug,
			&i.MediaKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesReleasedBetween = `-- name: ListGamesReleasedBetween :many
SELECT gc.id, gc.slug, gc.title, gc.tagline, gc.release_date, gc.release_status, gc.gem_score, gc.developer_name, gc.developer_slug, gc.media_key
FROM game_cards gc
WHERE gc.release_date >= $1 AND gc.release_date < $2
ORDER BY gc.release_date
`

type ListGamesReleasedBetweenParams struct {
	ReleaseDate   pgtype.Date
	ReleaseDate_2 pgtype.Date
}

// Weekly Release Radar: games released in [from, to), ordered by date
// (exclusive end, so callers pass Monday of the NEXT week).
func (q *Queries) ListGamesReleasedBetween(ctx context.Context, arg ListGamesReleasedBetweenParams) ([]GameCard, error) {
	rows, err := q.db.Query(ctx, listGamesReleasedBetween, arg.ReleaseDate, arg.ReleaseDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameCard
	for rows.Next() {
		var i GameCard
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Tagline,
			&i.ReleaseDate,
			&i.ReleaseStatus,
			&i.GemScore,
			&i.DeveloperName,
			&i.DeveloperSlug,
			&i.MediaKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoreLinks = `-- name: ListStoreLinks :many
SELECT game_id, store, url, source_url, updated_at FROM store_links
WHERE game_id = $1
ORDER BY store
`

func (q *Queries) ListStoreLinks(ctx context.Context, gameID pgtype.UUID) ([]StoreLink, error) {
	rows, err := q.db.Query(ctx, listStoreLinks, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoreLink
	for rows.Next() {
		var i StoreLink
		if err := rows.Scan(
			&i.GameID,
			&i.Store,
			&i.Url,
			&i.SourceUrl,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopGamesBetween = `-- name: ListTopGamesBetween :many
SELECT gc.id, gc.slug, gc.title, gc.tagline, gc.release_date, gc.release_status, gc.gem_score, gc.developer_name, gc.developer_slug, gc.media_key
FROM game_cards gc
WHERE gc.release_date >= $1 AND gc.release_date < $2
  AND gc.gem_score >= $3
ORDER BY gc.gem_score DESC
`

type ListTopGamesBetweenParams struct {
	ReleaseDate   pgtype.Date
	ReleaseDate_2 pgtype.Date
	GemScore      pgtype.Float4
}

// Top of the Month: best games by gem_score released in [from, to)
// (exclusive end, so {{top 2026-09}} never picks up next month's day 1);
// min_score filters the tail.
func (q *Queries) ListTopGamesBetween(ctx context.Context, arg ListTopGamesBetweenParams) ([]GameCard, error) {
	rows, err := q.db.Query(ctx, listTopGamesBetween, arg.ReleaseDate, arg.ReleaseDate_2, arg.GemScore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameCard
	for rows.Next() {
		var i GameCard
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Tagline,
			&i.ReleaseDate,
			&i.ReleaseStatus,
			&i.GemScore,
			&i.DeveloperName,
			&i.DeveloperSlug,
			&i.MediaKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
