// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cli.sql

package data

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGameDeveloperRoles = `-- name: DeleteGameDeveloperRoles :exec
DELETE FROM game_developers
WHERE game_id = $1 AND developer_id = $2 AND role = $3
`

type DeleteGameDeveloperRolesParams struct {
	GameID      pgtype.UUID
	DeveloperID pgtype.UUID
	Role        string
}

// Seed sync: drop roles no longer present in the seed file.
func (q *Queries) DeleteGameDeveloperRoles(ctx context.Context, arg DeleteGameDeveloperRolesParams) error {
	_, err := q.db.Exec(ctx, deleteGameDeveloperRoles, arg.GameID, arg.DeveloperID, arg.Role)
	return err
}

const deleteStoreLink = `-- name: DeleteStoreLink :exec
DELETE FROM store_links
WHERE game_id = $1 AND store = $2
`

type DeleteStoreLinkParams struct {
	GameID pgtype.UUID
	Store  string
}

func (q *Queries) DeleteStoreLink(ctx context.Context, arg DeleteStoreLinkParams) error {
	_, err := q.db.Exec(ctx, deleteStoreLink, arg.GameID, arg.Store)
	return err
}

const getDeveloperByID = `-- name: GetDeveloperByID :one
SELECT id, slug, name, bio_md, website_url, logo_key, socials, igdb_id, created_at, updated_at, last_igdb_sync_at FROM developers
WHERE id = $1
`

func (q *Queries) GetDeveloperByID(ctx context.Context, id pgtype.UUID) (Developer, error) {
	row := q.db.QueryRow(ctx, getDeveloperByID, id)
	var i Developer
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.BioMd,
		&i.WebsiteUrl,
		&i.LogoKey,
		&i.Socials,
		&i.IgdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastIgdbSyncAt,
	)
	return i, err
}

const getDeveloperByName = `-- name: GetDeveloperByName :one
SELECT id, slug, name, bio_md, website_url, logo_key, socials, igdb_id, created_at, updated_at, last_igdb_sync_at FROM developers
WHERE LOWER(name) = LOWER($1)
`

func (q *Queries) GetDeveloperByName(ctx context.Context, lower string) (Developer, error) {
	row := q.db.QueryRow(ctx, getDeveloperByName, lower)
	var i Developer
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.BioMd,
		&i.WebsiteUrl,
		&i.LogoKey,
		&i.Socials,
		&i.IgdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastIgdbSyncAt,
	)
	return i, err
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, slug, title, tagline, description_md, gem_note_md, release_date, release_status, steam_appid, igdb_id, website_url, steam_review_pct, steam_review_count, editorial_score, gem_score, created_at, updated_at, trailer_youtube_id, last_steam_sync_at, last_igdb_sync_at FROM games
WHERE id = $1
`

func (q *Queries) GetGameByID(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Tagline,
		&i.DescriptionMd,
		&i.GemNoteMd,
		&i.ReleaseDate,
		&i.ReleaseStatus,
		&i.SteamAppid,
		&i.IgdbID,
		&i.WebsiteUrl,
		&i.SteamReviewPct,
		&i.SteamReviewCount,
		&i.EditorialScore,
		&i.GemScore,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrailerYoutubeID,
		&i.LastSteamSyncAt,
		&i.LastIgdbSyncAt,
	)
	return i, err
}

const getGameBySteamAppID = `-- name: GetGameBySteamAppID :one
SELECT id, slug, title, tagline, description_md, gem_note_md, release_date, release_status, steam_appid, igdb_id, website_url, steam_review_pct, steam_review_count, editorial_score, gem_score, created_at, updated_at, trailer_youtube_id, last_steam_sync_at, last_igdb_sync_at FROM games
WHERE steam_appid = $1
`

func (q *Queries) GetGameBySteamAppID(ctx context.Context, steamAppid pgtype.Int8) (Game, error) {
	row := q.db.QueryRow(ctx, getGameBySteamAppID, steamAppid)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Tagline,
		&i.DescriptionMd,
		&i.GemNoteMd,
		&i.ReleaseDate,
		&i.ReleaseStatus,
		&i.SteamAppid,
		&i.IgdbID,
		&i.WebsiteUrl,
		&i.SteamReviewPct,
		&i.SteamReviewCount,
		&i.EditorialScore,
		&i.GemScore,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrailerYoutubeID,
		&i.LastSteamSyncAt,
		&i.LastIgdbSyncAt,
	)
	return i, err
}

const importDeveloper = `-- name: ImportDeveloper :one
INSERT INTO developers (slug, name, igdb_id)
VALUES ($1, $2, $3)
ON CONFLICT (slug) DO NOTHING
RETURNING id, slug, name, bio_md, website_url, logo_key, socials, igdb_id, created_at, updated_at, last_igdb_sync_at
`

type ImportDeveloperParams struct {
	Slug   string
	Name   string
	IgdbID pgtype.Int8
}

// Importer variant: never touches an existing developer with the same slug.
func (q *Queries) ImportDeveloper(ctx context.Context, arg ImportDeveloperParams) (Developer, error) {
	row := q.db.QueryRow(ctx, importDeveloper, arg.Slug, arg.Name, arg.IgdbID)
	var i Developer
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.BioMd,
		&i.WebsiteUrl,
		&i.LogoKey,
		&i.Socials,
		&i.IgdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastIgdbSyncAt,
	)
	return i, err
}

const importStoreLink = `-- name: ImportStoreLink :exec

INSERT INTO store_links (game_id, store, url, source_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (game_id, store) DO NOTHING
`

type ImportStoreLinkParams struct {
	GameID    pgtype.UUID
	Store     string
	Url       string
	SourceUrl string
}

// ============================================================================
// Phase-2 importers (steam/igdb sync, media fetch)
// ============================================================================
// Importer variant: never overwrites a store link that seed/curation set.
func (q *Queries) ImportStoreLink(ctx context.Context, arg ImportStoreLinkParams) error {
	_, err := q.db.Exec(ctx, importStoreLink,
		arg.GameID,
		arg.Store,
		arg.Url,
		arg.SourceUrl,
	)
	return err
}

const listDevelopers = `-- name: ListDevelopers :many
SELECT id, slug, name, bio_md, website_url, logo_key, socials, igdb_id, created_at, updated_at, last_igdb_sync_at FROM developers
ORDER BY slug
`

func (q *Queries) ListDevelopers(ctx context.Context) ([]Developer, error) {
	rows, err := q.db.Query(ctx, listDevelopers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Developer
	for rows.Next() {
		var i Developer
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.BioMd,
			&i.WebsiteUrl,
			&i.LogoKey,
			&i.Socials,
			&i.IgdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastIgdbSyncAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevelopersWithIGDBID = `-- name: ListDevelopersWithIGDBID :many
SELECT d.id, d.slug, d.name, d.igdb_id
FROM developers d
WHERE d.igdb_id IS NOT NULL
ORDER BY d.slug
`

type ListDevelopersWithIGDBIDRow struct {
	ID     pgtype.UUID
	Slug   string
	Name   string
	IgdbID pgtype.Int8
}

func (q *Queries) ListDevelopersWithIGDBID(ctx context.Context) ([]ListDevelopersWithIGDBIDRow, error) {
	rows, err := q.db.Query(ctx, listDevelopersWithIGDBID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevelopersWithIGDBIDRow
	for rows.Next() {
		var i ListDevelopersWithIGDBIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.IgdbID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameMediaKeys = `-- name: ListGameMediaKeys :many
SELECT key FROM media
WHERE game_id = $1
`

func (q *Queries) ListGameMediaKeys(ctx context.Context, gameID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listGameMediaKeys, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGames = `-- name: ListGames :many
SELECT id, slug, title, tagline, description_md, gem_note_md, release_date, release_status, steam_appid, igdb_id, website_url, steam_review_pct, steam_review_count, editorial_score, gem_score, created_at, updated_at, trailer_youtube_id, last_steam_sync_at, last_igdb_sync_at FROM games
ORDER BY title
`

// Full catalog rows for gems games list / rescore (scan on purpose).
func (q *Queries) ListGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Tagline,
			&i.DescriptionMd,
			&i.GemNoteMd,
			&i.ReleaseDate,
			&i.ReleaseStatus,
			&i.SteamAppid,
			&i.IgdbID,
			&i.WebsiteUrl,
			&i.SteamReviewPct,
			&i.SteamReviewCount,
			&i.EditorialScore,
			&i.GemScore,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrailerYoutubeID,
			&i.LastSteamSyncAt,
			&i.LastIgdbSyncAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesForSync = `-- name: ListGamesForSync :many
SELECT g.id, g.slug, g.title, g.steam_appid, g.igdb_id, g.trailer_youtube_id,
       g.last_steam_sync_at, g.last_igdb_sync_at
FROM games g
ORDER BY g.slug
`

type ListGamesForSyncRow struct {
	ID               pgtype.UUID
	Slug             string
	Title            string
	SteamAppid       pgtype.Int8
	IgdbID           pgtype.Int8
	TrailerYoutubeID pgtype.Text
	LastSteamSyncAt  pgtype.Timestamptz
	LastIgdbSyncAt   pgtype.Timestamptz
}

// Steam/IGDB sync + media-fetch candidates (admin projection).
func (q *Queries) ListGamesForSync(ctx context.Context) ([]ListGamesForSyncRow, error) {
	rows, err := q.db.Query(ctx, listGamesForSync)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGamesForSyncRow
	for rows.Next() {
		var i ListGamesForSyncRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.SteamAppid,
			&i.IgdbID,
			&i.TrailerYoutubeID,
			&i.LastSteamSyncAt,
			&i.LastIgdbSyncAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesMissingMedia = `-- name: ListGamesMissingMedia :many
SELECT g.id, g.slug, g.steam_appid, g.igdb_id, g.trailer_youtube_id
FROM games g
WHERE NOT EXISTS (
    SELECT 1 FROM media m
    WHERE m.game_id = g.id AND m.kind IN ('header', 'capsule', 'cover')
)
ORDER BY g.slug
`

type ListGamesMissingMediaRow struct {
	ID               pgtype.UUID
	Slug             string
	SteamAppid       pgtype.Int8
	IgdbID           pgtype.Int8
	TrailerYoutubeID pgtype.Text
}

// Games without a header/capsule card image yet (refresh targets).
func (q *Queries) ListGamesMissingMedia(ctx context.Context) ([]ListGamesMissingMediaRow, error) {
	rows, err := q.db.Query(ctx, listGamesMissingMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGamesMissingMediaRow
	for rows.Next() {
		var i ListGamesMissingMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.SteamAppid,
			&i.IgdbID,
			&i.TrailerYoutubeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeveloperIGDBSync = `-- name: SetDeveloperIGDBSync :exec
UPDATE developers
SET igdb_id = COALESCE(igdb_id, $2),
    bio_md = CASE WHEN bio_md = '' THEN $3 ELSE bio_md END,
    website_url = CASE WHEN website_url = '' THEN $4 ELSE website_url END,
    logo_key = CASE WHEN logo_key = '' THEN $5 ELSE logo_key END,
    last_igdb_sync_at = now()
WHERE id = $1
`

type SetDeveloperIGDBSyncParams struct {
	ID         pgtype.UUID
	IgdbID     pgtype.Int8
	BioMd      string
	WebsiteUrl string
	LogoKey    string
}

// IGDB importer merge for companies: igdb_id never clobbered; description,
// website and logo only fill gaps.
func (q *Queries) SetDeveloperIGDBSync(ctx context.Context, arg SetDeveloperIGDBSyncParams) error {
	_, err := q.db.Exec(ctx, setDeveloperIGDBSync,
		arg.ID,
		arg.IgdbID,
		arg.BioMd,
		arg.WebsiteUrl,
		arg.LogoKey,
	)
	return err
}

const setGameIGDBSync = `-- name: SetGameIGDBSync :exec
UPDATE games
SET igdb_id = COALESCE(igdb_id, $2),
    trailer_youtube_id = COALESCE(trailer_youtube_id, $3),
    last_igdb_sync_at = now()
WHERE id = $1
`

type SetGameIGDBSyncParams struct {
	ID               pgtype.UUID
	IgdbID           pgtype.Int8
	TrailerYoutubeID pgtype.Text
}

// IGDB importer merge: never clobber an existing igdb_id or trailer.
func (q *Queries) SetGameIGDBSync(ctx context.Context, arg SetGameIGDBSyncParams) error {
	_, err := q.db.Exec(ctx, setGameIGDBSync, arg.ID, arg.IgdbID, arg.TrailerYoutubeID)
	return err
}

const setGameScores = `-- name: SetGameScores :exec
UPDATE games
SET editorial_score = $2,
    steam_review_pct = $3,
    steam_review_count = $4,
    gem_score = $5
WHERE id = $1
`

type SetGameScoresParams struct {
	ID               pgtype.UUID
	EditorialScore   pgtype.Int2
	SteamReviewPct   pgtype.Int2
	SteamReviewCount int64
	GemScore         pgtype.Float4
}

// Recomputed inputs + gem_score; called by gems rescore and after seed.
func (q *Queries) SetGameScores(ctx context.Context, arg SetGameScoresParams) error {
	_, err := q.db.Exec(ctx, setGameScores,
		arg.ID,
		arg.EditorialScore,
		arg.SteamReviewPct,
		arg.SteamReviewCount,
		arg.GemScore,
	)
	return err
}

const setGameSteamSync = `-- name: SetGameSteamSync :exec
UPDATE games
SET description_md = $2,
    steam_review_pct = $3,
    steam_review_count = $4,
    website_url = CASE WHEN website_url = '' THEN $5 ELSE website_url END,
    release_date = COALESCE(release_date, $6),
    release_status = CASE
        WHEN release_date IS NULL AND release_status = 'announced' THEN $7
        ELSE release_status END,
    last_steam_sync_at = now()
WHERE id = $1
`

type SetGameSteamSyncParams struct {
	ID               pgtype.UUID
	DescriptionMd    string
	SteamReviewPct   pgtype.Int2
	SteamReviewCount int64
	WebsiteUrl       string
	ReleaseDate      pgtype.Date
	ReleaseStatus    string
}

// Steam importer merge: curated fields always win. Only description, review
// stats, empty website, and a missing release date/status are filled.
func (q *Queries) SetGameSteamSync(ctx context.Context, arg SetGameSteamSyncParams) error {
	_, err := q.db.Exec(ctx, setGameSteamSync,
		arg.ID,
		arg.DescriptionMd,
		arg.SteamReviewPct,
		arg.SteamReviewCount,
		arg.WebsiteUrl,
		arg.ReleaseDate,
		arg.ReleaseStatus,
	)
	return err
}

const setGameWebsiteIfEmpty = `-- name: SetGameWebsiteIfEmpty :exec
UPDATE games
SET website_url = CASE WHEN website_url = '' THEN $2 ELSE website_url END
WHERE id = $1
`

type SetGameWebsiteIfEmptyParams struct {
	ID         pgtype.UUID
	WebsiteUrl string
}

func (q *Queries) SetGameWebsiteIfEmpty(ctx context.Context, arg SetGameWebsiteIfEmptyParams) error {
	_, err := q.db.Exec(ctx, setGameWebsiteIfEmpty, arg.ID, arg.WebsiteUrl)
	return err
}

const upsertDeveloper = `-- name: UpsertDeveloper :one

INSERT INTO developers (slug, name, bio_md, website_url, socials, igdb_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name,
    bio_md = COALESCE(NULLIF(EXCLUDED.bio_md, ''), developers.bio_md),
    website_url = COALESCE(NULLIF(EXCLUDED.website_url, ''), developers.website_url),
    socials = EXCLUDED.socials,
    igdb_id = COALESCE(EXCLUDED.igdb_id, developers.igdb_id)
RETURNING id, slug, name, bio_md, website_url, logo_key, socials, igdb_id, created_at, updated_at, last_igdb_sync_at
`

type UpsertDeveloperParams struct {
	Slug       string
	Name       string
	BioMd      string
	WebsiteUrl string
	Socials    []byte
	IgdbID     pgtype.Int8
}

// CLI upserts / admin (gems seed, link, rescore, games list).
// Seed upsert. Seed owns name/socials; importer-owned igdb_id, bio_md,
// website_url and logo_key are only filled when the seed provides a
// non-empty value (or never, for igdb_id).
func (q *Queries) UpsertDeveloper(ctx context.Context, arg UpsertDeveloperParams) (Developer, error) {
	row := q.db.QueryRow(ctx, upsertDeveloper,
		arg.Slug,
		arg.Name,
		arg.BioMd,
		arg.WebsiteUrl,
		arg.Socials,
		arg.IgdbID,
	)
	var i Developer
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.BioMd,
		&i.WebsiteUrl,
		&i.LogoKey,
		&i.Socials,
		&i.IgdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastIgdbSyncAt,
	)
	return i, err
}

const upsertGame = `-- name: UpsertGame :one
INSERT INTO games (slug, title, tagline, description_md, gem_note_md,
                   release_date, release_status, steam_appid, igdb_id,
                   website_url, editorial_score)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (slug) DO UPDATE
SET title = EXCLUDED.title,
    tagline = EXCLUDED.tagline,
    description_md = COALESCE(NULLIF(EXCLUDED.description_md, ''), games.description_md),
    gem_note_md = EXCLUDED.gem_note_md,
    release_date = EXCLUDED.release_date,
    release_status = EXCLUDED.release_status,
    steam_appid = EXCLUDED.steam_appid,
    igdb_id = COALESCE(EXCLUDED.igdb_id, games.igdb_id),
    website_url = COALESCE(NULLIF(EXCLUDED.website_url, ''), games.website_url),
    editorial_score = EXCLUDED.editorial_score
RETURNING id, slug, title, tagline, description_md, gem_note_md, release_date, release_status, steam_appid, igdb_id, website_url, steam_review_pct, steam_review_count, editorial_score, gem_score, created_at, updated_at, trailer_youtube_id, last_steam_sync_at, last_igdb_sync_at
`

type UpsertGameParams struct {
	Slug           string
	Title          string
	Tagline        string
	DescriptionMd  string
	GemNoteMd      string
	ReleaseDate    pgtype.Date
	ReleaseStatus  string
	SteamAppid     pgtype.Int8
	IgdbID         pgtype.Int8
	WebsiteUrl     string
	EditorialScore pgtype.Int2
}

// Seed upsert. Field ownership: seed owns title, tagline, gem_note_md,
// release_date/status, steam_appid, editorial_score. Importer-owned fields
// (description_md, website_url) are only overwritten when the seed provides
// a non-empty value, so re-seeding never wipes Steam/IGDB data. Review
// stats, igdb_id, trailer and sync timestamps aren't touched at all.
func (q *Queries) UpsertGame(ctx context.Context, arg UpsertGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, upsertGame,
		arg.Slug,
		arg.Title,
		arg.Tagline,
		arg.DescriptionMd,
		arg.GemNoteMd,
		arg.ReleaseDate,
		arg.ReleaseStatus,
		arg.SteamAppid,
		arg.IgdbID,
		arg.WebsiteUrl,
		arg.EditorialScore,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Tagline,
		&i.DescriptionMd,
		&i.GemNoteMd,
		&i.ReleaseDate,
		&i.ReleaseStatus,
		&i.SteamAppid,
		&i.IgdbID,
		&i.WebsiteUrl,
		&i.SteamReviewPct,
		&i.SteamReviewCount,
		&i.EditorialScore,
		&i.GemScore,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrailerYoutubeID,
		&i.LastSteamSyncAt,
		&i.LastIgdbSyncAt,
	)
	return i, err
}

const upsertGameDeveloperRole = `-- name: UpsertGameDeveloperRole :exec
INSERT INTO game_developers (game_id, developer_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (game_id, developer_id, role) DO NOTHING
`

type UpsertGameDeveloperRoleParams struct {
	GameID      pgtype.UUID
	DeveloperID pgtype.UUID
	Role        string
}

func (q *Queries) UpsertGameDeveloperRole(ctx context.Context, arg UpsertGameDeveloperRoleParams) error {
	_, err := q.db.Exec(ctx, upsertGameDeveloperRole, arg.GameID, arg.DeveloperID, arg.Role)
	return err
}

const upsertGameTag = `-- name: UpsertGameTag :exec
INSERT INTO game_tags (game_id, tag_id)
VALUES ($1, $2)
ON CONFLICT (game_id, tag_id) DO NOTHING
`

type UpsertGameTagParams struct {
	GameID pgtype.UUID
	TagID  pgtype.UUID
}

func (q *Queries) UpsertGameTag(ctx context.Context, arg UpsertGameTagParams) error {
	_, err := q.db.Exec(ctx, upsertGameTag, arg.GameID, arg.TagID)
	return err
}

const upsertMedia = `-- name: UpsertMedia :one
INSERT INTO media (game_id, kind, key, source_url, position)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (key) DO UPDATE
SET game_id = EXCLUDED.game_id,
    kind = EXCLUDED.kind,
    source_url = EXCLUDED.source_url,
    position = EXCLUDED.position
RETURNING id, game_id, kind, key, source_url, position, created_at, updated_at
`

type UpsertMediaParams struct {
	GameID    pgtype.UUID
	Kind      string
	Key       string
	SourceUrl string
	Position  int16
}

// Media cache row by key; keys are content-addressed paths under MEDIA_DIR.
func (q *Queries) UpsertMedia(ctx context.Context, arg UpsertMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, upsertMedia,
		arg.GameID,
		arg.Kind,
		arg.Key,
		arg.SourceUrl,
		arg.Position,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Kind,
		&i.Key,
		&i.SourceUrl,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStoreLink = `-- name: UpsertStoreLink :exec
INSERT INTO store_links (game_id, store, url, source_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (game_id, store) DO UPDATE
SET url = EXCLUDED.url,
    source_url = EXCLUDED.source_url
`

type UpsertStoreLinkParams struct {
	GameID    pgtype.UUID
	Store     string
	Url       string
	SourceUrl string
}

func (q *Queries) UpsertStoreLink(ctx context.Context, arg UpsertStoreLinkParams) error {
	_, err := q.db.Exec(ctx, upsertStoreLink,
		arg.GameID,
		arg.Store,
		arg.Url,
		arg.SourceUrl,
	)
	return err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (slug, name)
VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name
RETURNING id, slug, name, created_at, updated_at
`

type UpsertTagParams struct {
	Slug string
	Name string
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag, arg.Slug, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
