// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: newsletter.sql

package data

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingDeliveries = `-- name: ClaimPendingDeliveries :many
WITH reclaimed AS (
    UPDATE deliveries
    SET status = 'pending', claimed_at = NULL
    WHERE deliveries.issue_id = $1 AND deliveries.status = 'sending'
      AND deliveries.claimed_at < $3
), skipped AS (
    UPDATE deliveries d
    SET status = 'skipped', claimed_at = NULL
    FROM subscribers s
    WHERE d.subscriber_id = s.id
      AND d.issue_id = $1
      AND d.status = 'pending'
      AND s.status <> 'confirmed'
), claimed AS (
    UPDATE deliveries d
    SET status = 'sending', claimed_at = now()
    WHERE d.id IN (
        SELECT c.id
        FROM deliveries c
        JOIN subscribers s ON s.id = c.subscriber_id
        WHERE c.issue_id = $1
          AND c.status = 'pending'
          AND c.attempts < $2
          AND s.status = 'confirmed'
        ORDER BY c.created_at
        FOR UPDATE OF c SKIP LOCKED
        LIMIT $4
    )
    RETURNING d.id, d.attempts, d.subscriber_id
)
SELECT c.id, c.attempts, c.subscriber_id, s.email
FROM claimed c
JOIN subscribers s ON s.id = c.subscriber_id
ORDER BY s.email
`

type ClaimPendingDeliveriesParams struct {
	IssueID   pgtype.UUID
	Attempts  int16
	ClaimedAt pgtype.Timestamptz
	Limit     int32
}

type ClaimPendingDeliveriesRow struct {
	ID           pgtype.UUID
	Attempts     int16
	SubscriberID pgtype.UUID
	Email        string
}

// Atomically claim a batch of work for one send run. One statement does
// three things under a single snapshot:
//  1. reclaim crashed claims: 'sending' rows whose claim is older than $3
//     (the claim holder died between SMTP accept and the DB update —
//     reclaiming trades at-most-once for that edge; documented in send.go);
//  2. skip subscribers who are no longer confirmed (unsubscribed mid-send):
//     their pending row moves to terminal 'skipped' so completion works;
//  3. claim pending rows FOR UPDATE / SKIP LOCKED, flipping them to
//     'sending' with a claim stamp — a concurrent run cannot claim them.
//
// Returns the claimed batch with recipient addresses.
func (q *Queries) ClaimPendingDeliveries(ctx context.Context, arg ClaimPendingDeliveriesParams) ([]ClaimPendingDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimPendingDeliveries,
		arg.IssueID,
		arg.Attempts,
		arg.ClaimedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimPendingDeliveriesRow
	for rows.Next() {
		var i ClaimPendingDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Attempts,
			&i.SubscriberID,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const confirmSubscriber = `-- name: ConfirmSubscriber :one
UPDATE subscribers
SET status = 'confirmed',
    confirmed_at = now(),
    confirmation_token_hash = NULL,
    confirmation_expires_at = NULL,
    updated_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, email, status, confirmation_token_hash, confirmation_expires_at, source, created_at, confirmed_at, unsubscribed_at, updated_at
`

// Double-opt-in completion: single-use token (hash cleared), consent stamped.
func (q *Queries) ConfirmSubscriber(ctx context.Context, id pgtype.UUID) (Subscriber, error) {
	row := q.db.QueryRow(ctx, confirmSubscriber, id)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.ConfirmationTokenHash,
		&i.ConfirmationExpiresAt,
		&i.Source,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.UnsubscribedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countConfirmedSubscribers = `-- name: CountConfirmedSubscribers :one
SELECT count(*)::bigint FROM subscribers WHERE status = 'confirmed'
`

func (q *Queries) CountConfirmedSubscribers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countConfirmedSubscribers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countDeliveriesByStatus = `-- name: CountDeliveriesByStatus :many
SELECT status, count(*)::bigint AS n
FROM deliveries
WHERE issue_id = $1
GROUP BY status
`

type CountDeliveriesByStatusRow struct {
	Status string
	N      int64
}

func (q *Queries) CountDeliveriesByStatus(ctx context.Context, issueID pgtype.UUID) ([]CountDeliveriesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countDeliveriesByStatus, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDeliveriesByStatusRow
	for rows.Next() {
		var i CountDeliveriesByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSubscribersByStatus = `-- name: CountSubscribersByStatus :many
SELECT status, count(*)::bigint AS n
FROM subscribers
GROUP BY status
ORDER BY status
`

type CountSubscribersByStatusRow struct {
	Status string
	N      int64
}

func (q *Queries) CountSubscribersByStatus(ctx context.Context) ([]CountSubscribersByStatusRow, error) {
	rows, err := q.db.Query(ctx, countSubscribersByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountSubscribersByStatusRow
	for rows.Next() {
		var i CountSubscribersByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSubscriber = `-- name: CreateSubscriber :one

INSERT INTO subscribers (email, source, confirmation_token_hash, confirmation_expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, status, confirmation_token_hash, confirmation_expires_at, source, created_at, confirmed_at, unsubscribed_at, updated_at
`

type CreateSubscriberParams struct {
	Email                 string
	Source                string
	ConfirmationTokenHash pgtype.Text
	ConfirmationExpiresAt pgtype.Timestamptz
}

// Newsletter: subscribers (double opt-in), issues and deliveries.
//
// Subscriber state transitions live in newsletter/state.go; this file is
// the persistence only. Index notes: email lookups use the unique
// lower(email) index, confirm-by-hash the partial confirmation_token_hash
// index, pending-delivery scans idx_deliveries_issue_pending, lookups by id
// the PKs.
func (q *Queries) CreateSubscriber(ctx context.Context, arg CreateSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRow(ctx, createSubscriber,
		arg.Email,
		arg.Source,
		arg.ConfirmationTokenHash,
		arg.ConfirmationExpiresAt,
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.ConfirmationTokenHash,
		&i.ConfirmationExpiresAt,
		&i.Source,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.UnsubscribedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredConfirmationToken = `-- name: DeleteExpiredConfirmationToken :exec
UPDATE subscribers
SET confirmation_token_hash = NULL,
    confirmation_expires_at = NULL
WHERE confirmation_expires_at < now()
`

// Housekeeping: forget the hash once the link can no longer be honoured.
func (q *Queries) DeleteExpiredConfirmationToken(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredConfirmationToken)
	return err
}

const ensureDeliveries = `-- name: EnsureDeliveries :execrows

INSERT INTO deliveries (issue_id, subscriber_id)
SELECT $1, s.id
FROM subscribers s
WHERE s.status = 'confirmed'
ON CONFLICT (issue_id, subscriber_id) DO NOTHING
`

// Deliveries ----------------------------------------------------------
// One row per current confirmed subscriber; re-runs are no-ops for pairs
// that already exist (UNIQUE issue_id+subscriber_id).
func (q *Queries) EnsureDeliveries(ctx context.Context, issueID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, ensureDeliveries, issueID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIssueByID = `-- name: GetIssueByID :one
SELECT id, slug, subject, preheader, source_md, html, text, status, sent_at, created_at, updated_at FROM issues
WHERE id = $1
`

func (q *Queries) GetIssueByID(ctx context.Context, id pgtype.UUID) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueByID, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Subject,
		&i.Preheader,
		&i.SourceMd,
		&i.Html,
		&i.Text,
		&i.Status,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssueBySlug = `-- name: GetIssueBySlug :one
SELECT id, slug, subject, preheader, source_md, html, text, status, sent_at, created_at, updated_at FROM issues
WHERE slug = $1
`

func (q *Queries) GetIssueBySlug(ctx context.Context, slug string) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueBySlug, slug)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Subject,
		&i.Preheader,
		&i.SourceMd,
		&i.Html,
		&i.Text,
		&i.Status,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPickOnOrBeforeWithDate = `-- name: GetPickOnOrBeforeWithDate :one
SELECT p.pick_date, p.note_md, game_cards.id, game_cards.slug, game_cards.title, game_cards.tagline, game_cards.release_date, game_cards.release_status, game_cards.gem_score, game_cards.developer_name, game_cards.developer_slug, game_cards.media_key
FROM game_cards
JOIN daily_picks p ON p.game_id = game_cards.id
WHERE p.pick_date <= $1
ORDER BY p.pick_date DESC
LIMIT 1
`

type GetPickOnOrBeforeWithDateRow struct {
	PickDate pgtype.Date
	NoteMd   string
	GameCard GameCard
}

// Game of the Day for the newsletter: like picks.GetLatestPickOnOrBefore
// but also returns the pick_date, which the Gotd heading shows.
func (q *Queries) GetPickOnOrBeforeWithDate(ctx context.Context, pickDate pgtype.Date) (GetPickOnOrBeforeWithDateRow, error) {
	row := q.db.QueryRow(ctx, getPickOnOrBeforeWithDate, pickDate)
	var i GetPickOnOrBeforeWithDateRow
	err := row.Scan(
		&i.PickDate,
		&i.NoteMd,
		&i.GameCard.ID,
		&i.GameCard.Slug,
		&i.GameCard.Title,
		&i.GameCard.Tagline,
		&i.GameCard.ReleaseDate,
		&i.GameCard.ReleaseStatus,
		&i.GameCard.GemScore,
		&i.GameCard.DeveloperName,
		&i.GameCard.DeveloperSlug,
		&i.GameCard.MediaKey,
	)
	return i, err
}

const getSentIssueBySlug = `-- name: GetSentIssueBySlug :one
SELECT slug, subject, html, text, sent_at
FROM issues
WHERE slug = $1 AND status = 'sent'
`

type GetSentIssueBySlugRow struct {
	Slug    string
	Subject string
	Html    string
	Text    string
	SentAt  pgtype.Timestamptz
}

// Web archive: only sent issues are publicly readable; drafts 404.
func (q *Queries) GetSentIssueBySlug(ctx context.Context, slug string) (GetSentIssueBySlugRow, error) {
	row := q.db.QueryRow(ctx, getSentIssueBySlug, slug)
	var i GetSentIssueBySlugRow
	err := row.Scan(
		&i.Slug,
		&i.Subject,
		&i.Html,
		&i.Text,
		&i.SentAt,
	)
	return i, err
}

const getSubscriberByConfirmationHash = `-- name: GetSubscriberByConfirmationHash :one
SELECT id, email, status, confirmation_token_hash, confirmation_expires_at, source, created_at, confirmed_at, unsubscribed_at, updated_at FROM subscribers
WHERE confirmation_token_hash = $1
`

func (q *Queries) GetSubscriberByConfirmationHash(ctx context.Context, confirmationTokenHash pgtype.Text) (Subscriber, error) {
	row := q.db.QueryRow(ctx, getSubscriberByConfirmationHash, confirmationTokenHash)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.ConfirmationTokenHash,
		&i.ConfirmationExpiresAt,
		&i.Source,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.UnsubscribedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriberByEmail = `-- name: GetSubscriberByEmail :one
SELECT id, email, status, confirmation_token_hash, confirmation_expires_at, source, created_at, confirmed_at, unsubscribed_at, updated_at FROM subscribers
WHERE lower(email) = $1
`

func (q *Queries) GetSubscriberByEmail(ctx context.Context, email string) (Subscriber, error) {
	row := q.db.QueryRow(ctx, getSubscriberByEmail, email)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.ConfirmationTokenHash,
		&i.ConfirmationExpiresAt,
		&i.Source,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.UnsubscribedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriberByID = `-- name: GetSubscriberByID :one
SELECT id, email, status, confirmation_token_hash, confirmation_expires_at, source, created_at, confirmed_at, unsubscribed_at, updated_at FROM subscribers
WHERE id = $1
`

func (q *Queries) GetSubscriberByID(ctx context.Context, id pgtype.UUID) (Subscriber, error) {
	row := q.db.QueryRow(ctx, getSubscriberByID, id)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.ConfirmationTokenHash,
		&i.ConfirmationExpiresAt,
		&i.Source,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.UnsubscribedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIssue = `-- name: InsertIssue :one

INSERT INTO issues (slug, subject, preheader, source_md, html, text)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, slug, subject, preheader, source_md, html, text, status, sent_at, created_at, updated_at
`

type InsertIssueParams struct {
	Slug      string
	Subject   string
	Preheader string
	SourceMd  string
	Html      string
	Text      string
}

// Issues ------------------------------------------------------------
func (q *Queries) InsertIssue(ctx context.Context, arg InsertIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, insertIssue,
		arg.Slug,
		arg.Subject,
		arg.Preheader,
		arg.SourceMd,
		arg.Html,
		arg.Text,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Subject,
		&i.Preheader,
		&i.SourceMd,
		&i.Html,
		&i.Text,
		&i.Status,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const issueHasDeliveries = `-- name: IssueHasDeliveries :one
SELECT EXISTS (SELECT 1 FROM deliveries WHERE issue_id = $1) AS has_deliveries
`

// Snapshot freeze rule: once any delivery row exists for an issue its
// rendered content is frozen (send-time consistency for resumed runs).
func (q *Queries) IssueHasDeliveries(ctx context.Context, issueID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, issueHasDeliveries, issueID)
	var has_deliveries bool
	err := row.Scan(&has_deliveries)
	return has_deliveries, err
}

const listIssues = `-- name: ListIssues :many
SELECT id, slug, subject, preheader, source_md, html, text, status, sent_at, created_at, updated_at FROM issues
ORDER BY created_at DESC
`

func (q *Queries) ListIssues(ctx context.Context) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Subject,
			&i.Preheader,
			&i.SourceMd,
			&i.Html,
			&i.Text,
			&i.Status,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentIssues = `-- name: ListSentIssues :many
SELECT slug, subject, sent_at
FROM issues
WHERE status = 'sent'
ORDER BY sent_at DESC
`

type ListSentIssuesRow struct {
	Slug    string
	Subject string
	SentAt  pgtype.Timestamptz
}

// Web archive index: only sent issues are public; drafts never leak.
func (q *Queries) ListSentIssues(ctx context.Context) ([]ListSentIssuesRow, error) {
	rows, err := q.db.Query(ctx, listSentIssues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSentIssuesRow
	for rows.Next() {
		var i ListSentIssuesRow
		if err := rows.Scan(&i.Slug, &i.Subject, &i.SentAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribers = `-- name: ListSubscribers :many
SELECT id, email, status, confirmation_token_hash, confirmation_expires_at, source, created_at, confirmed_at, unsubscribed_at, updated_at FROM subscribers
ORDER BY created_at, email
`

func (q *Queries) ListSubscribers(ctx context.Context) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, listSubscribers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Status,
			&i.ConfirmationTokenHash,
			&i.ConfirmationExpiresAt,
			&i.Source,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.UnsubscribedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryFailed = `-- name: MarkDeliveryFailed :execrows
UPDATE deliveries
SET status = 'failed', attempts = attempts + 1, last_error = $2,
    claimed_at = NULL
WHERE id = $1 AND status = 'sending'
`

type MarkDeliveryFailedParams struct {
	ID        pgtype.UUID
	LastError string
}

// Park as failed after max attempts (claim released).
func (q *Queries) MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDeliveryFailed, arg.ID, arg.LastError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDeliverySent = `-- name: MarkDeliverySent :execrows
UPDATE deliveries
SET status = 'sent', sent_at = now(), attempts = attempts + 1,
    last_error = '', claimed_at = NULL
WHERE id = $1 AND status = 'sending'
`

// Guarded by status='sending': only the run holding the claim may complete
// it, so a slow run cannot mark a row another run already reclaimed.
func (q *Queries) MarkDeliverySent(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markDeliverySent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markIssueSent = `-- name: MarkIssueSent :execrows
UPDATE issues
SET status = 'sent', sent_at = now(), updated_at = now()
WHERE id = $1 AND status = 'draft'
`

func (q *Queries) MarkIssueSent(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markIssueSent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSubscriberUnsubscribed = `-- name: MarkSubscriberUnsubscribed :one
UPDATE subscribers
SET status = 'unsubscribed',
    unsubscribed_at = COALESCE(unsubscribed_at, now()),
    updated_at = now()
WHERE id = $1
RETURNING id, email, status, confirmation_token_hash, confirmation_expires_at, source, created_at, confirmed_at, unsubscribed_at, updated_at
`

// Idempotent opt-out (RFC 8058 retries must succeed): re-running keeps the
// FIRST withdrawal timestamp as consent proof.
func (q *Queries) MarkSubscriberUnsubscribed(ctx context.Context, id pgtype.UUID) (Subscriber, error) {
	row := q.db.QueryRow(ctx, markSubscriberUnsubscribed, id)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.ConfirmationTokenHash,
		&i.ConfirmationExpiresAt,
		&i.Source,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.UnsubscribedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordDeliveryFailure = `-- name: RecordDeliveryFailure :execrows
UPDATE deliveries
SET status = 'pending', attempts = attempts + 1, last_error = $2,
    claimed_at = NULL
WHERE id = $1 AND status = 'sending'
`

type RecordDeliveryFailureParams struct {
	ID        pgtype.UUID
	LastError string
}

// Release a failed attempt back to pending for retry (attempt counted,
// claim released).
func (q *Queries) RecordDeliveryFailure(ctx context.Context, arg RecordDeliveryFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordDeliveryFailure, arg.ID, arg.LastError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resubscribeSubscriber = `-- name: ResubscribeSubscriber :one
UPDATE subscribers
SET status = 'pending',
    confirmation_token_hash = $2,
    confirmation_expires_at = $3,
    unsubscribed_at = NULL,
    updated_at = now()
WHERE id = $1 AND status = 'unsubscribed'
RETURNING id, email, status, confirmation_token_hash, confirmation_expires_at, source, created_at, confirmed_at, unsubscribed_at, updated_at
`

type ResubscribeSubscriberParams struct {
	ID                    pgtype.UUID
	ConfirmationTokenHash pgtype.Text
	ConfirmationExpiresAt pgtype.Timestamptz
}

// Explicit new signup over an unsubscribed address: back to pending with a
// fresh token. created_at keeps the original signup; the new consent is
// stamped on confirm.
func (q *Queries) ResubscribeSubscriber(ctx context.Context, arg ResubscribeSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRow(ctx, resubscribeSubscriber, arg.ID, arg.ConfirmationTokenHash, arg.ConfirmationExpiresAt)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.ConfirmationTokenHash,
		&i.ConfirmationExpiresAt,
		&i.Source,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.UnsubscribedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSubscriberConfirmationToken = `-- name: SetSubscriberConfirmationToken :exec
UPDATE subscribers
SET confirmation_token_hash = $2,
    confirmation_expires_at = $3,
    updated_at = now()
WHERE id = $1 AND status = 'pending'
`

type SetSubscriberConfirmationTokenParams struct {
	ID                    pgtype.UUID
	ConfirmationTokenHash pgtype.Text
	ConfirmationExpiresAt pgtype.Timestamptz
}

// (Re)sent confirmation mail for a pending signup: fresh token + expiry.
func (q *Queries) SetSubscriberConfirmationToken(ctx context.Context, arg SetSubscriberConfirmationTokenParams) error {
	_, err := q.db.Exec(ctx, setSubscriberConfirmationToken, arg.ID, arg.ConfirmationTokenHash, arg.ConfirmationExpiresAt)
	return err
}

const updateIssueSnapshot = `-- name: UpdateIssueSnapshot :one
UPDATE issues
SET subject = $2, preheader = $3, source_md = $4, html = $5, text = $6,
    updated_at = now()
WHERE slug = $1 AND status = 'draft'
  AND NOT EXISTS (SELECT 1 FROM deliveries WHERE issue_id = issues.id)
RETURNING id, slug, subject, preheader, source_md, html, text, status, sent_at, created_at, updated_at
`

type UpdateIssueSnapshotParams struct {
	Slug      string
	Subject   string
	Preheader string
	SourceMd  string
	Html      string
	Text      string
}

// Re-send authoring loop: refresh the draft's snapshot. Two guards:
// sent issues are immutable, and a draft whose deliveries already exist is
// frozen — content must not change once any recipient row was created, or
// resumed sends would deliver different content than the first batch.
func (q *Queries) UpdateIssueSnapshot(ctx context.Context, arg UpdateIssueSnapshotParams) (Issue, error) {
	row := q.db.QueryRow(ctx, updateIssueSnapshot,
		arg.Slug,
		arg.Subject,
		arg.Preheader,
		arg.SourceMd,
		arg.Html,
		arg.Text,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Subject,
		&i.Preheader,
		&i.SourceMd,
		&i.Html,
		&i.Text,
		&i.Status,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
