// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package data

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGamesReleasedBetween = `-- name: CountGamesReleasedBetween :one
SELECT COUNT(*)::int AS count
FROM game_cards
WHERE release_date >= $1 AND release_date < $2
`

type CountGamesReleasedBetweenParams struct {
	ReleaseDate   pgtype.Date
	ReleaseDate_2 pgtype.Date
}

// Home "Top of the Month" checks whether the current month is thin enough to
// fall back to the previous one. release_date range: idx_games_release_date.
func (q *Queries) CountGamesReleasedBetween(ctx context.Context, arg CountGamesReleasedBetweenParams) (int32, error) {
	row := q.db.QueryRow(ctx, countGamesReleasedBetween, arg.ReleaseDate, arg.ReleaseDate_2)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getLatestPickDateOnOrBefore = `-- name: GetLatestPickDateOnOrBefore :one
SELECT MAX(pick_date)::date AS pick_date
FROM daily_picks
WHERE pick_date <= $1
`

// The date the "latest pick so far" fallback actually landed on (needed for
// the canonical URL and date label when today has no pick).
func (q *Queries) GetLatestPickDateOnOrBefore(ctx context.Context, pickDate pgtype.Date) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getLatestPickDateOnOrBefore, pickDate)
	var pick_date pgtype.Date
	err := row.Scan(&pick_date)
	return pick_date, err
}

const listAllDeveloperSlugs = `-- name: ListAllDeveloperSlugs :many
SELECT slug FROM developers ORDER BY slug
`

// Sitemap.
func (q *Queries) ListAllDeveloperSlugs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAllDeveloperSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCuratedGems = `-- name: ListCuratedGems :many

SELECT gc.id, gc.slug, gc.title, gc.tagline, gc.release_date, gc.release_status, gc.gem_score, gc.developer_name, gc.developer_slug, gc.media_key
FROM game_cards gc
WHERE gc.release_status = 'released'
  AND gc.gem_score IS NOT NULL
ORDER BY gc.gem_score DESC
LIMIT $1
`

// Page-facing read queries (SELECT only) for the public website handlers.
// Card-returning queries use the game_cards view so every listing shares
// data.GameCard. Index notes are per query; the catalog is small, so sorts
// over a few filtered rows are fine.
// Home "curated gems": highest-scoring released games. Seq scan + top-N sort
// is correct here; catalog size makes an index (gem_score) not worth its
// write amplification (revisit at ~10k games).
func (q *Queries) ListCuratedGems(ctx context.Context, limit int32) ([]GameCard, error) {
	rows, err := q.db.Query(ctx, listCuratedGems, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameCard
	for rows.Next() {
		var i GameCard
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Tagline,
			&i.ReleaseDate,
			&i.ReleaseStatus,
			&i.GemScore,
			&i.DeveloperName,
			&i.DeveloperSlug,
			&i.MediaKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeveloperGames = `-- name: ListDeveloperGames :many
SELECT DISTINCT ON (gc.id) gc.id, gc.slug, gc.title, gc.tagline, gc.release_date, gc.release_status, gc.gem_score, gc.developer_name, gc.developer_slug, gc.media_key
FROM game_cards gc
JOIN game_developers gd
  ON gd.game_id = gc.id
 AND gd.developer_id = $1
ORDER BY gc.id, gd.role
`

// Every game a developer is attached to, in any role. developer_id is served
// by idx_game_developers_developer; DISTINCT ON dedupes the company being
// both developer and publisher. Ordered by id for DISTINCT ON; the handler
// re-sorts newest-first for display.
func (q *Queries) ListDeveloperGames(ctx context.Context, developerID pgtype.UUID) ([]GameCard, error) {
	rows, err := q.db.Query(ctx, listDeveloperGames, developerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameCard
	for rows.Next() {
		var i GameCard
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Tagline,
			&i.ReleaseDate,
			&i.ReleaseStatus,
			&i.GemScore,
			&i.DeveloperName,
			&i.DeveloperSlug,
			&i.MediaKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPicks = `-- name: ListRecentPicks :many
SELECT game_cards.id, game_cards.slug, game_cards.title, game_cards.tagline, game_cards.release_date, game_cards.release_status, game_cards.gem_score, game_cards.developer_name, game_cards.developer_slug, game_cards.media_key, p.pick_date, p.note_md
FROM game_cards
JOIN daily_picks p ON p.game_id = game_cards.id
WHERE p.pick_date <= $1
ORDER BY p.pick_date DESC
LIMIT $2
`

type ListRecentPicksParams struct {
	PickDate pgtype.Date
	Limit    int32
}

type ListRecentPicksRow struct {
	GameCard GameCard
	PickDate pgtype.Date
	NoteMd   string
}

// Game of the Day archive + RSS feed: latest picks at or before `before`.
// pick_date filter/order is served by daily_picks_pkey.
func (q *Queries) ListRecentPicks(ctx context.Context, arg ListRecentPicksParams) ([]ListRecentPicksRow, error) {
	rows, err := q.db.Query(ctx, listRecentPicks, arg.PickDate, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentPicksRow
	for rows.Next() {
		var i ListRecentPicksRow
		if err := rows.Scan(
			&i.GameCard.ID,
			&i.GameCard.Slug,
			&i.GameCard.Title,
			&i.GameCard.Tagline,
			&i.GameCard.ReleaseDate,
			&i.GameCard.ReleaseStatus,
			&i.GameCard.GemScore,
			&i.GameCard.DeveloperName,
			&i.GameCard.DeveloperSlug,
			&i.GameCard.MediaKey,
			&i.PickDate,
			&i.NoteMd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentlyReleased = `-- name: ListRecentlyReleased :many
SELECT id, slug, title, tagline, release_date, release_status, gem_score, developer_name, developer_slug, media_key
FROM game_cards
WHERE release_date < $1
ORDER BY release_date DESC
LIMIT $2
`

type ListRecentlyReleasedParams struct {
	ReleaseDate pgtype.Date
	Limit       int32
}

// Home radar row filler, last resort: most recent releases before `before`
// (the start of the current week). release_date range: idx_games_release_date.
func (q *Queries) ListRecentlyReleased(ctx context.Context, arg ListRecentlyReleasedParams) ([]GameCard, error) {
	rows, err := q.db.Query(ctx, listRecentlyReleased, arg.ReleaseDate, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameCard
	for rows.Next() {
		var i GameCard
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Tagline,
			&i.ReleaseDate,
			&i.ReleaseStatus,
			&i.GemScore,
			&i.DeveloperName,
			&i.DeveloperSlug,
			&i.MediaKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopGames = `-- name: ListTopGames :many
SELECT gc.id, gc.slug, gc.title, gc.tagline, gc.release_date, gc.release_status, gc.gem_score, gc.developer_name, gc.developer_slug, gc.media_key
FROM game_cards gc
WHERE gc.release_date >= $1 AND gc.release_date < $2
ORDER BY gc.gem_score DESC NULLS LAST
LIMIT $3
`

type ListTopGamesParams struct {
	ReleaseDate   pgtype.Date
	ReleaseDate_2 pgtype.Date
	Limit         int32
}

// Top of the Month (page + home section): best games by gem_score released
// in [from, to). release_date range is served by idx_games_release_date.
func (q *Queries) ListTopGames(ctx context.Context, arg ListTopGamesParams) ([]GameCard, error) {
	rows, err := q.db.Query(ctx, listTopGames, arg.ReleaseDate, arg.ReleaseDate_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameCard
	for rows.Next() {
		var i GameCard
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Tagline,
			&i.ReleaseDate,
			&i.ReleaseStatus,
			&i.GemScore,
			&i.DeveloperName,
			&i.DeveloperSlug,
			&i.MediaKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingGames = `-- name: ListUpcomingGames :many
SELECT id, slug, title, tagline, release_date, release_status, gem_score, developer_name, developer_slug, media_key
FROM game_cards
WHERE release_date >= $1
ORDER BY release_date ASC
LIMIT $2
`

type ListUpcomingGamesParams struct {
	ReleaseDate pgtype.Date
	Limit       int32
}

// Home radar row filler: next dated releases after `from` (the end of the
// current week), soonest first. release_date range: idx_games_release_date.
func (q *Queries) ListUpcomingGames(ctx context.Context, arg ListUpcomingGamesParams) ([]GameCard, error) {
	rows, err := q.db.Query(ctx, listUpcomingGames, arg.ReleaseDate, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameCard
	for rows.Next() {
		var i GameCard
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Tagline,
			&i.ReleaseDate,
			&i.ReleaseStatus,
			&i.GemScore,
			&i.DeveloperName,
			&i.DeveloperSlug,
			&i.MediaKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
