// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: picks.sql

package data

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDailyPick = `-- name: DeleteDailyPick :exec
DELETE FROM daily_picks
WHERE pick_date = $1
`

func (q *Queries) DeleteDailyPick(ctx context.Context, pickDate pgtype.Date) error {
	_, err := q.db.Exec(ctx, deleteDailyPick, pickDate)
	return err
}

const getDailyPick = `-- name: GetDailyPick :one

SELECT game_cards.id, game_cards.slug, game_cards.title, game_cards.tagline, game_cards.release_date, game_cards.release_status, game_cards.gem_score, game_cards.developer_name, game_cards.developer_slug, game_cards.media_key, p.note_md
FROM game_cards
JOIN daily_picks p ON p.game_id = game_cards.id
WHERE p.pick_date = $1
`

type GetDailyPickRow struct {
	GameCard GameCard
	NoteMd   string
}

// Daily picks (Game of the Day). Pick rows join game_cards so page views get
// the full card (embedded as data.GameCards) plus the editorial note.
func (q *Queries) GetDailyPick(ctx context.Context, pickDate pgtype.Date) (GetDailyPickRow, error) {
	row := q.db.QueryRow(ctx, getDailyPick, pickDate)
	var i GetDailyPickRow
	err := row.Scan(
		&i.GameCard.ID,
		&i.GameCard.Slug,
		&i.GameCard.Title,
		&i.GameCard.Tagline,
		&i.GameCard.ReleaseDate,
		&i.GameCard.ReleaseStatus,
		&i.GameCard.GemScore,
		&i.GameCard.DeveloperName,
		&i.GameCard.DeveloperSlug,
		&i.GameCard.MediaKey,
		&i.NoteMd,
	)
	return i, err
}

const getLatestPickOnOrBefore = `-- name: GetLatestPickOnOrBefore :one
SELECT game_cards.id, game_cards.slug, game_cards.title, game_cards.tagline, game_cards.release_date, game_cards.release_status, game_cards.gem_score, game_cards.developer_name, game_cards.developer_slug, game_cards.media_key, p.note_md
FROM game_cards
JOIN daily_picks p ON p.game_id = game_cards.id
WHERE p.pick_date <= $1
ORDER BY p.pick_date DESC
LIMIT 1
`

type GetLatestPickOnOrBeforeRow struct {
	GameCard GameCard
	NoteMd   string
}

func (q *Queries) GetLatestPickOnOrBefore(ctx context.Context, pickDate pgtype.Date) (GetLatestPickOnOrBeforeRow, error) {
	row := q.db.QueryRow(ctx, getLatestPickOnOrBefore, pickDate)
	var i GetLatestPickOnOrBeforeRow
	err := row.Scan(
		&i.GameCard.ID,
		&i.GameCard.Slug,
		&i.GameCard.Title,
		&i.GameCard.Tagline,
		&i.GameCard.ReleaseDate,
		&i.GameCard.ReleaseStatus,
		&i.GameCard.GemScore,
		&i.GameCard.DeveloperName,
		&i.GameCard.DeveloperSlug,
		&i.GameCard.MediaKey,
		&i.NoteMd,
	)
	return i, err
}

const getNextPickDate = `-- name: GetNextPickDate :one
SELECT MIN(pick_date)::date AS pick_date
FROM daily_picks
WHERE pick_date > $1
`

func (q *Queries) GetNextPickDate(ctx context.Context, pickDate pgtype.Date) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getNextPickDate, pickDate)
	var pick_date pgtype.Date
	err := row.Scan(&pick_date)
	return pick_date, err
}

const getPreviousPickDate = `-- name: GetPreviousPickDate :one
SELECT MAX(pick_date)::date AS pick_date
FROM daily_picks
WHERE pick_date < $1
`

func (q *Queries) GetPreviousPickDate(ctx context.Context, pickDate pgtype.Date) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getPreviousPickDate, pickDate)
	var pick_date pgtype.Date
	err := row.Scan(&pick_date)
	return pick_date, err
}

const listGamesForPickRotation = `-- name: ListGamesForPickRotation :many
SELECT g.id, g.slug, g.title, g.gem_score
FROM games g
ORDER BY g.gem_score DESC NULLS LAST, g.slug
`

type ListGamesForPickRotationRow struct {
	ID       pgtype.UUID
	Slug     string
	Title    string
	GemScore pgtype.Float4
}

// Candidate games for gems pick auto, best first.
func (q *Queries) ListGamesForPickRotation(ctx context.Context) ([]ListGamesForPickRotationRow, error) {
	rows, err := q.db.Query(ctx, listGamesForPickRotation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGamesForPickRotationRow
	for rows.Next() {
		var i ListGamesForPickRotationRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.GemScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPicksBetween = `-- name: ListPicksBetween :many
SELECT p.pick_date, p.note_md, g.slug, g.title
FROM daily_picks p
JOIN games g ON g.id = p.game_id
WHERE p.pick_date BETWEEN $1 AND $2
ORDER BY p.pick_date
`

type ListPicksBetweenParams struct {
	PickDate   pgtype.Date
	PickDate_2 pgtype.Date
}

type ListPicksBetweenRow struct {
	PickDate pgtype.Date
	NoteMd   string
	Slug     string
	Title    string
}

func (q *Queries) ListPicksBetween(ctx context.Context, arg ListPicksBetweenParams) ([]ListPicksBetweenRow, error) {
	rows, err := q.db.Query(ctx, listPicksBetween, arg.PickDate, arg.PickDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPicksBetweenRow
	for rows.Next() {
		var i ListPicksBetweenRow
		if err := rows.Scan(
			&i.PickDate,
			&i.NoteMd,
			&i.Slug,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyPick = `-- name: UpsertDailyPick :exec
INSERT INTO daily_picks (pick_date, game_id, note_md)
VALUES ($1, $2, $3)
ON CONFLICT (pick_date) DO UPDATE
SET game_id = EXCLUDED.game_id,
    note_md = EXCLUDED.note_md
`

type UpsertDailyPickParams struct {
	PickDate pgtype.Date
	GameID   pgtype.UUID
	NoteMd   string
}

func (q *Queries) UpsertDailyPick(ctx context.Context, arg UpsertDailyPickParams) error {
	_, err := q.db.Exec(ctx, upsertDailyPick, arg.PickDate, arg.GameID, arg.NoteMd)
	return err
}
